clusternet/website

- content/en/releases/2022-03-04-Release-v0.8.0.md
Signed-off-by: “yiwei-C” <yiwei.chen24@gmail.com>
> Added v0.8.0 release notes

- content/en/releases/2022-03-04-Release-v0.9.0.md
- content/en/releases/2022-03-04-Release-v0.9.1.md
Signed-off-by: Yiwei Chen <yiwei.chen24@gmail.com>
> Added v0.9.0, v0.9.1 release notes

- config/_default/menus.en.toml
- content/en/_index.md
- content/en/proposals/_index.md
- content/en/proposals/template.md
> add folder for proposals

- Makefile
- netlify.toml
> install postcss js package

- config.toml
- content/zh-cn/_index.html
- content/zh-cn/community/_index.md
- content/zh-cn/docs/_index.md
- content/zh-cn/featured-background.jpg
- content/zh-cn/search.md
> add zh-cn folder

- content/zh-cn/docs/tutorials/deploy-to-multiple-clusters.md
Add Chinese documents
Fixes #9
> Add Chinese documents

- README.md
- config.toml
- content/en/docs/developer-guide.md
- content/en/docs/installation/install-the-hard-way.md
- content/en/docs/installation/install-with-helm.md
- content/en/docs/kubectl-clusternet.md
- content/en/docs/quick-start.md
- content/en/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/construct-a-dedicated-kubeconfig.md
- content/en/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-curl.md
- content/zh-cn/docs/developer-guide.md
- content/zh-cn/docs/installation/install-the-hard-way.md
- content/zh-cn/docs/installation/install-with-helm.md
- content/zh-cn/docs/kubectl-clusternet.md
- content/zh-cn/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/construct-a-dedicated-kubeconfig.md
- content/zh-cn/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-curl.md
> fix scripts format

- content/en/docs/tutorials/multi-cluster-apps/aggregated-status.md
- content/en/docs/tutorials/multi-cluster-apps/dynamic-scheduling-to-multiple-clusters.md
- content/en/docs/tutorials/multi-cluster-apps/replication-scheduling-to-multiple-clusters.md
- content/en/docs/tutorials/multi-cluster-apps/setting-overrides.md
- content/en/docs/tutorials/multi-cluster-apps/static-weight-scheduling-to-multiple-clusters.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/_index.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/aggregated-status.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/dynamic-scheduling-to-multiple-clusters.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/replication-scheduling-to-multiple-clusters.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/setting-overrides.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/static-weight-scheduling-to-multiple-clusters.md
> add docs on dynamic scheduling and status aggregation

- content/zh-cn/docs/quick-start.md
> Chinese version of getting started to use Clusternet

- content/en/docs/tutorials/using-client-go-in-clusternet.md
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Fixes #10
> docs: translate `using client-go in Clusternet` to chinese

- content/zh-cn/docs/developer-guide.md
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Fixes #7
> docs: translate developer guide

- content/en/docs/tutorials/using-client-go-in-clusternet.md
- content/zh-cn/docs/tutorials/using-client-go-in-clusternet.md
> fix en zh-cn versions of client-go doc

- content/en/docs/installation/install-the-hard-way.md
- content/en/docs/installation/install-with-helm.md
- content/en/docs/tutorials/cluster-management/checking-cluster-registration.md
- content/zh-cn/docs/installation/install-the-hard-way.md
- content/zh-cn/docs/installation/install-with-helm.md
- content/zh-cn/docs/tutorials/cluster-management/checking-cluster-registration.md
> fix docs missing links and translations

- content/zh-cn/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/_index.md
- content/zh-cn/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/construct-a-dedicated-kubeconfig.md
- content/zh-cn/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-curl.md
- content/zh-cn/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-kubectl-clusternet.md
translate document，pls check it
> translate docs on child cluster visiting

- content/en/docs/tutorials/service-management/_index.md
- content/en/docs/tutorials/service-management/visting-services-child-cluster-port-forward.md
- content/zh-cn/docs/tutorials/service-management/_index.md
- content/zh-cn/docs/tutorials/service-management/visting-services-child-cluster-port-forward.md
> visiting services with port-forward

- content/zh-cn/docs/installation/install-the-hard-way.md
Signed-off-by: ConanYao <JaneConan@live.com>
What type of PR is this?
translate install-the-hard-way guide to Chinese
Implement https://github.com/clusternet/website/issues/12
> translate install-the-hard-way guide to Chinese (#12)

- content/en/docs/tutorials/multi-cluster-apps/replication-scheduling-to-multiple-clusters.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/replication-scheduling-to-multiple-clusters.md
> Fix typos in demo.

- content/zh-cn/docs/user-guide/clusternet-shadow-api.md
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Fixes #48
> docs: Chinese version of Clusternet shadow APIs

- content/en/docs/tutorials/mutil-cluster-service/visting-services-in-child-cluster.md
- content/zh-cn/docs/tutorials/mutil-cluster-service/visting-services-in-child-cluster.md
related issue : https://github.com/clusternet/clusternet/issues/508
Signed-off-by: lmxia <xialingming@gmail.com>
> fix mcs serviceimport demo path error

- content/zh-cn/docs/user-guide/use-localization-and-globalization.md
Signed-off-by: Amos [albert7king@gmail.com](albert7king@gmail.com)
What type of PR is this?
translate use-localization-and-globalization to Chinese
Fixes #51
> translate use-localization-and-globalization to Chinese

- content/en/docs/configuration/helm-chart.md
- content/zh-cn/docs/configuration/helm-chart.md
> add replaceCRDs

- content/en/docs/user-guide/integrate-with-submariner.md
- content/zh-cn/docs/user-guide/integrate-with-submariner.md
Add docs about aggregation with submariner.
> add doc description about subamariner aggregate

- content/zh-cn/docs/concepts.md
- content/zh-cn/docs/configuration/aggregator-forwarding-redirect.md
- content/zh-cn/docs/quick-start.md
- content/zh-cn/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-kubectl-clusternet.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/_index.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/aggregated-status.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/dynamic-scheduling-to-multiple-clusters.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/replication-scheduling-to-multiple-clusters.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/setting-overrides.md
- content/zh-cn/docs/tutorials/multi-cluster-apps/static-weight-scheduling-to-multiple-clusters.md
add zh doc for multi-cluster-apps and quick-start，and fix some link to /zh-doc/
> add zh doc for multi-cluster-apps and quick-start

- content/en/docs/tutorials/mutil-cluster-service/visting-services-in-child-cluster.md
- content/zh-cn/docs/tutorials/mutil-cluster-service/visting-services-in-child-cluster.md
Add a little description of mcs featuregate.
> add mcs featuregate description

- content/en/docs/configuration/feature-gates.md
- content/zh-cn/docs/configuration/feature-gates.md
xref clusternet/clusternet#705
> add doc for feature gate FeasibleClustersToleration

- content/en/docs/installation/install-on-k3s.md
- content/zh-cn/docs/installation/install-on-k3s.md
Fixes clusternet/clusternet#717
> docs: add k3s installation guide

- content/en/docs/tutorials/multi-cluster-apps/replication-scheduling-to-multiple-clusters.md
Fixes clusternet/clusternet#799
> fix: example url

- content/en/docs/tutorials/mutil-cluster-service/_index.md
- content/en/docs/tutorials/mutil-cluster-service/visting-services-in-child-cluster.md
- content/zh-cn/docs/tutorials/mutil-cluster-service/_index.md
- content/zh-cn/docs/tutorials/mutil-cluster-service/visting-services-in-child-cluster.md
Change website about tutorials in mcs demo to Fleetboard.
> change mcs to fleetboard

- content/en/_index.html
> update link in homepage
